name: ros_nodes
description: A custom ros communication library for dart
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml_rpc:
    git:
      url: https://github.com/a-blue-pig/dart-xmlrpc.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
